name: NikitaForest CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "NikitaForest/**"
      - ".github/workflows/nikitaforest-ci.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "NikitaForest/**"

jobs:
  html-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install HTMLHint
        run: npm i -g htmlhint

      - name: Run HTMLHint
        run: |
          htmlhint "NikitaForest/**/*.html"

      - name: Check broken links
        uses: lycheeverse/lychee-action@v1
        with:
          args: NikitaForest/**/*.html
